name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 18
          - 20
        architecture:
          - x64
    env:
      GRAPHQL_GITHUB_API_TOKEN: ${{ secrets.GRAPHQL_GITHUB_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
          cache: yarn
      - name: Install Dependencies
        run: |
          npm install @sudoo/build-cli -g
          yarn
      - name: Lint
        run: |
          yarn lint
      - name: Build
        run: |
          yarn build
      - name: Test
        run: |
          sudoo-build --type typescript-react coverage
      - name: Codecov
        uses: codecov/codecov-action@v3
